from classes.repo import Repo
from classes.car import Car
from classes.cell import Cell, Decoration, Checkpoint, Obstacle, Bonus, Booster, Refuel, Road, StraightRoad, StraightAxisAlignedRoad, StraightDiagonalRoad, Turn90

Repo().components.register("Car", Car)
Repo().components.register("Cell", Cell)
Repo().components.register("Decoration", Decoration)
Repo().components.register("Checkpoint", Checkpoint)
Repo().components.register("Obstacle", Obstacle)
Repo().components.register("Bonus", Bonus)
Repo().components.register("Booster", Booster)
Repo().components.register("Refuel", Refuel)
Repo().components.register("Road", Road)
Repo().components.register("StraightRoad", StraightRoad)
Repo().components.register("StraightAxisAlignedRoad", StraightAxisAlignedRoad)
Repo().components.register("StraightDiagonalRoad", StraightDiagonalRoad)
Repo().components.register("Turn90", Turn90)
Repo().components.list()

map_id = Repo.create(cols=10, rows=10, cellsize=64, bgcolor='green') # map has an id of 0
Repo.attach(map_id, "batuhan")
Repo.listattached("batuhan") # 0 will be listed
map_instance = Repo.getObjectOfUser(map_id, "batuhan")
map_instance[(0, 0)] = Decoration(0, 0, 0)
for i in range(2, 8):
    map_instance[(1, i)] = StraightAxisAlignedRoad(1, i, 0)
map_instance[(1, 7)] = Turn90(1, 7, 1)
for i in range(2, 6):
    map_instance[(i, 7)] = StraightAxisAlignedRoad(i, 7, 1)
map_instance[(8, 9)] = Obstacle(8, 9, 0)
print(map_instance[(8, 9)].type())
print(map_instance.getxy(75, 150).type())
refuel = Refuel(15 // 64, 250 // 64, 0)
print(map_instance.place(refuel, 15, 250))
map_instance.draw()

volvo_XC60 = Repo().components.create("Car", model="Volvo-XC60", map_ref=map_instance, driver="batuhan", pos=(1,1), angle=0, topspeed=100, topfuel=100)
volvo_XC60.draw()

sub_map = map_instance.view(3, 1, 5, 5)
sub_map.draw()

volvo_XC60.start()
volvo_XC60.tick()
volvo_XC60.accel()
volvo_XC60.tick()
volvo_XC60.tick()
volvo_XC60.tick()
volvo_XC60.left()
volvo_XC60.tick()
volvo_XC60.right()
volvo_XC60.tick()
volvo_XC60.right()
volvo_XC60.tick()
volvo_XC60.tick()
volvo_XC60.accel()
volvo_XC60.tick()
volvo_XC60.right()
volvo_XC60.tick()
volvo_XC60.right()
volvo_XC60.tick()
volvo_XC60.right()
volvo_XC60.tick()
volvo_XC60.right()
volvo_XC60.tick()
volvo_XC60.brake()
volvo_XC60.tick()
volvo_XC60.brake()
volvo_XC60.tick()
volvo_XC60.stop()
volvo_XC60.accel()
volvo_XC60.tick()