# Generated by Django 5.1.4 on 2024-12-14 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RaceMapApp', '0003_remove_player_name_remove_player_surname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
