# Generated by Django 5.1.4 on 2024-12-15 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaceMapApp', '0006_componentregistry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='componentregistry',
            name='id',
        ),
        migrations.AlterField(
            model_name='componentregistry',
            name='type',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('y', models.IntegerField()),
                ('rotation', models.IntegerField(choices=[(0, 'ZERO'), (1, 'ONE'), (2, 'TWO'), (3, 'THREE')], default=0)),
                ('map_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RaceMapApp.map')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RaceMapApp.componentregistry')),
            ],
        ),
    ]
