# Generated by Django 5.1.4 on 2024-12-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaceMapApp', '0008_rename_map_id_component_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='rotation',
            field=models.IntegerField(default=0),
        ),
    ]
