# Generated by Django 5.1.4 on 2024-12-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaceMapApp', '0013_alter_map_bg_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='bg_color',
            field=models.CharField(choices=[('BLUE', 'BLUE'), ('RED', 'RED'), ('GREEN', 'GREEN'), ('WHITE', 'WHITE'), ('BLACK', 'BLACK'), ('ORANGE', 'ORANGE'), ('PINK', 'PINK'), ('GRAY', 'GRAY'), ('YELLOW', 'YELLOW'), ('PURPLE', 'PURPLE')], default='WHITE', max_length=10),
        ),
    ]
