# Generated by Django 5.1.4 on 2024-12-14 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RaceMapApp', '0002_player_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='surname',
        ),
    ]
