# Generated by Django 5.1.4 on 2024-12-15 15:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('RaceMapApp', '0004_delete_player'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('num_cols', models.IntegerField()),
                ('num_rows', models.IntegerField()),
                ('cellsize', models.IntegerField()),
                ('bg_color', models.CharField(max_length=20)),
                ('users', models.ManyToManyField(related_name='maps', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
