# Generated by Django 5.1.4 on 2024-12-15 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaceMapApp', '0005_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentRegistry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, unique=True)),
                ('is_registered', models.BooleanField()),
            ],
        ),
    ]
