# Generated by Django 5.1.4 on 2024-12-15 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RaceMapApp', '0007_remove_componentregistry_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='map_id',
            new_name='map',
        ),
    ]
