# Generated by Django 5.1.4 on 2024-12-17 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaceMapApp', '0011_alter_car_model_car_map_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='bg_color',
            field=models.CharField(choices=[('BL', 'Blue'), ('RD', 'Red'), ('GR', 'Green'), ('WH', 'White'), ('BK', 'Black'), ('OR', 'Orange'), ('PI', 'Pink'), ('GY', 'Gray'), ('YE', 'Yellow'), ('PU', 'Purple')], default='WH', max_length=2),
        ),
    ]
