# Generated by Django 5.1.4 on 2024-12-17 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RaceMapApp', '0012_alter_map_bg_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='bg_color',
            field=models.CharField(choices=[('BL', 'BLUE'), ('RD', 'RED'), ('GR', 'GREEN'), ('WH', 'WHITE'), ('BK', 'BLACK'), ('OR', 'ORANGE'), ('PI', 'PINK'), ('GY', 'GRAY'), ('YE', 'YELLOW'), ('PU', 'PURPLE')], default='WH', max_length=2),
        ),
    ]
